### ISSUE TITLE
Docker in development

### ISSUE THREAD

**Issue by Bernardoow** [jarrekk/django-tmpl#1]
Hi,

Is possible sharer source file with docker?

Example: When I change file in local host then docker detect change and rerun server.  I need the same workflow when I run python manage.py runserver in local.

**Comment by jarrekk** [comment]
I use PyCharm to process coding. In development, I go to dir **docker_compose/devleopment** and run `docker-compose up` to start basic services with my project will connect them: MySQL, rabbitmq, redis. When I change code, project will reload.

`./manage.py runserver` is the same.

**Comment by Bernardoow** [comment]
Ah ok.

Can u change this dev~ to use Postgress?

**Comment by jarrekk** [comment]
Postgres seems better, later I will add this feature.
